[package]
name = "swear_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
enum_dispatch = "0.3.13"
fastrand = "2.1.0"
swear_parser = { path = "swear_parser" }
# swear_lib_macros = { path = "swear_lib_macros"}
lalrpop-util = "0.20.2"
dyn-clone = "1.0.17"

[build]
target-dir = "../target"
