[package]
name = "swear_parser"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
enum_dispatch = "0.3.13"
lalrpop-util = { version = "0.20.2", features = [ "lexer" ] }

[build]
target-dir = "../../target"
